// ============================================================
// 3LACKD CRM — Mock data + i18n
// ============================================================

const I18N = {
 pt: {
 // Nav
 dashboard: "Dashboard",
 pipeline: "Pipeline",
 accounts: "Contas e Leads",
 schedule: "Agenda",
 reports: "Relatórios",
 team: "Equipe",
 settings: "Configurações",
 coverage: "Abrangência",
 routing: "Roteirização",
 catalog: "Catálogo",
 message: "Mensagem",
 send: "Enviar",
 whatsapp: "WhatsApp",
 email_label: "Email",
 generate_pdf: "Gerar catálogo PDF",
 // Sections
 main: "Principal",
 operation: "Operação",
 insights: "Insights",
 // Topbar
 search_placeholder: "Buscar contas, leads, atividades…",
 new: "Novo",
 new_deal: "Nova oportunidade",
 new_lead: "Novo lead",
 filter: "Filtrar",
 sort: "Ordenar",
 export: "Exportar",
 import: "Importar",
 // Dashboard
 welcome: "Bom dia, Camila",
 dash_sub: "Aqui está o que está acontecendo no seu canal interno hoje.",
 revenue_forecast: "Projeção de faturamento",
 revenue_forecast_sub: "Próximos 90 dias, ponderado por probabilidade",
 active_deals: "Oportunidades ativas",
 pipeline_value: "Valor em pipeline",
 closing_this_month: "Fechando este mês",
 avg_cycle: "Ciclo médio",
 avg_cycle_unit: "dias",
 activity: "Atividade recente",
 upcoming: "Próximas atividades",
 by_segment: "Performance por segmento",
 top_reps: "Top vendedores",
 inactivity_alerts: "Alertas de inatividade",
 inactivity_sub: "Contas sem contato no prazo definido",
 days_silent: "dias sem contato",
 reactivate: "Reativar",
 funnel: "Funil de conversão",
 // Brand banner
 banner_title: "Meta do mês: R$ 4.8M",
 banner_sub: "Você está 12% acima da projeção. Mantenha o ritmo nas oportunidades em negociação.",
 // Pipeline
 stages: {
 new: "Novo",
 qualified: "Qualificado",
 proposal: "Proposta",
 negotiation: "Negociação",
 won: "Ganho",
 lost: "Perdido",
 },
 add_card: "+ Adicionar",
 // Accounts
 all_accounts: "Todas as contas",
 new_leads: "Leads novos",
 inactive: "Inativos",
 customers: "Clientes",
 // Detail tabs
 overview: "Visão geral",
 activities: "Atividades",
 contacts: "Contatos",
 proposals: "Propostas",
 contract: "Contrato",
 buying_behavior: "Comportamento de compra",
 notes: "Notas",
 // Calendar
 today: "Hoje",
 week: "Semana",
 month: "Mês",
 // Reports
 revenue: "Faturamento",
 quota_attainment: "Atingimento de meta",
 conversion: "Conversão por estágio",
 territory: "Abrangência por região",
 // Team
 rep: "Vendedor",
 quota: "Meta",
 closed: "Fechado",
 calls: "Ligações",
 meetings: "Reuniões",
 win_rate: "Taxa de ganho",
 // Settings
 commercial_policy: "Política comercial",
 contracts: "Contratos",
 inactivity: "Inatividade",
 integrations: "Integrações",
 team_perms: "Equipe e permissões",
 pipeline_stages: "Estágios do pipeline",
 // Misc
 days_ago: "há {n} dias",
 save: "Salvar",
 cancel: "Cancelar",
 edit: "Editar",
 delete: "Excluir",
 close: "Fechar",
 open_record: "Abrir registro",
 last_contact: "Último contato",
 next_step: "Próximo passo",
 deal_value: "Valor da oportunidade",
 probability: "Probabilidade",
 expected_close: "Previsão de fechamento",
 industry: "Setor",
 region: "Região",
 owner: "Responsável",
 status: "Status",
 company: "Empresa",
 contact: "Contato",
 stage: "Estágio",
 created: "Criado",
 },
 en: {
 dashboard: "Dashboard",
 pipeline: "Pipeline",
 accounts: "Accounts & Leads",
 schedule: "Calendar",
 reports: "Reports",
 team: "Team",
 settings: "Settings",
 coverage: "Coverage",
 routing: "Routing",
 catalog: "Catalog",
 message: "Message",
 send: "Send",
 whatsapp: "WhatsApp",
 email_label: "Email",
 generate_pdf: "Generate catalog PDF",
 main: "Main",
 operation: "Operations",
 insights: "Insights",
 search_placeholder: "Search accounts, leads, activities…",
 new: "New",
 new_deal: "New deal",
 new_lead: "New lead",
 filter: "Filter",
 sort: "Sort",
 export: "Export",
 import: "Import",
 welcome: "Good morning, Camila",
 dash_sub: "Here's what's happening on your sales channel today.",
 revenue_forecast: "Revenue forecast",
 revenue_forecast_sub: "Next 90 days, probability-weighted",
 active_deals: "Active deals",
 pipeline_value: "Pipeline value",
 closing_this_month: "Closing this month",
 avg_cycle: "Avg. cycle",
 avg_cycle_unit: "days",
 activity: "Recent activity",
 upcoming: "Upcoming activities",
 by_segment: "Performance by segment",
 top_reps: "Top reps",
 inactivity_alerts: "Inactivity alerts",
 inactivity_sub: "Accounts past the defined silence threshold",
 days_silent: "days silent",
 reactivate: "Reactivate",
 funnel: "Conversion funnel",
 banner_title: "Monthly target: R$ 4.8M",
 banner_sub: "You're 12% above forecast. Keep momentum on deals in negotiation.",
 stages: {
 new: "New",
 qualified: "Qualified",
 proposal: "Proposal",
 negotiation: "Negotiation",
 won: "Won",
 lost: "Lost",
 },
 add_card: "+ Add",
 all_accounts: "All accounts",
 new_leads: "New leads",
 inactive: "Inactive",
 customers: "Customers",
 overview: "Overview",
 activities: "Activities",
 contacts: "Contacts",
 proposals: "Proposals",
 contract: "Contract",
 buying_behavior: "Buying behavior",
 notes: "Notes",
 today: "Today",
 week: "Week",
 month: "Month",
 revenue: "Revenue",
 quota_attainment: "Quota attainment",
 conversion: "Conversion by stage",
 territory: "Coverage by region",
 rep: "Rep",
 quota: "Quota",
 closed: "Closed",
 calls: "Calls",
 meetings: "Meetings",
 win_rate: "Win rate",
 commercial_policy: "Commercial policy",
 contracts: "Contracts",
 inactivity: "Inactivity",
 integrations: "Integrations",
 team_perms: "Team & permissions",
 pipeline_stages: "Pipeline stages",
 days_ago: "{n} days ago",
 save: "Save",
 cancel: "Cancel",
 edit: "Edit",
 delete: "Delete",
 close: "Close",
 open_record: "Open record",
 last_contact: "Last contact",
 next_step: "Next step",
 deal_value: "Deal value",
 probability: "Probability",
 expected_close: "Expected close",
 industry: "Industry",
 region: "Region",
 owner: "Owner",
 status: "Status",
 company: "Company",
 contact: "Contact",
 stage: "Stage",
 created: "Created",
 },
};

// ============================================================
// Mock pipeline data
// ============================================================
const STAGES = [
 { id: "new", color: "#8A8899", dotClass: "dot-new" },
 { id: "qualified", color: "#4A8BC8", dotClass: "dot-qual" },
 { id: "proposal", color: "#2EBFC5", dotClass: "dot-prop" },
 { id: "negotiation", color: "#D88514", dotClass: "dot-neg" },
 { id: "won", color: "#16A07C", dotClass: "dot-won" },
];

const INDUSTRIES = [
 { id: "metallurgy", pt: "Metalúrgica", en: "Metallurgy" },
 { id: "food", pt: "Alimentos", en: "Food & Beverage" },
 { id: "chemistry", pt: "Química", en: "Chemicals" },
 { id: "textile", pt: "Têxtil", en: "Textile" },
 { id: "automotive", pt: "Automotivo", en: "Automotive" },
 { id: "plastics", pt: "Plásticos", en: "Plastics" },
 { id: "electronics", pt: "Eletrônicos", en: "Electronics" },
 { id: "construction", pt: "Construção", en: "Construction" },
];

const REGIONS = ["Sul", "Sudeste", "Centro-Oeste", "Nordeste", "Norte"];

const REPS = [
 { id: "u1", name: "Camila Reis", initials: "CR", color: "#2EBFC5", role: "Coord. Comercial" },
 { id: "u2", name: "Diego Almeida", initials: "DA", color: "#3F5BA8", role: "Sr. Sales Rep" },
 { id: "u3", name: "Júlia Marques", initials: "JM", color: "#7B5BC8", role: "Sales Rep" },
 { id: "u4", name: "Rafael Costa", initials: "RC", color: "#16A07C", role: "Sales Rep" },
 { id: "u5", name: "Mariana Tavares", initials: "MT", color: "#D88514", role: "Inside Sales" },
 { id: "u6", name: "Lucas Vianna", initials: "LV", color: "#D63B5C", role: "Inside Sales" },
];

const ACCOUNTS = [
 { id: "a1", name: "Metalúrgica Aurora", industry: "metallurgy", region: "Sul", city: "Caxias do Sul, RS", employees: 320, owner: "u2", lastContact: 2, inactive: false, customer: false },
 { id: "a2", name: "Frigorífico SulCarne", industry: "food", region: "Sul", city: "Passo Fundo, RS", employees: 1100, owner: "u3", lastContact: 5, inactive: false, customer: true },
 { id: "a3", name: "QuímicaTech Indústria",industry: "chemistry", region: "Sudeste", city: "Campinas, SP", employees: 480, owner: "u4", lastContact: 12, inactive: false, customer: false },
 { id: "a4", name: "Tecidos Cipriani", industry: "textile", region: "Sul", city: "Brusque, SC", employees: 210, owner: "u5", lastContact: 28, inactive: true, customer: false },
 { id: "a5", name: "AutoPeças Bahiana", industry: "automotive", region: "Nordeste", city: "Camaçari, BA", employees: 640, owner: "u2", lastContact: 1, inactive: false, customer: false },
 { id: "a6", name: "PolyBrasil Plásticos", industry: "plastics", region: "Sudeste", city: "São José dos Campos, SP",employees: 540, owner: "u3", lastContact: 8, inactive: false, customer: false },
 { id: "a7", name: "EletroMaster Norte", industry: "electronics",region: "Norte", city: "Manaus, AM", employees: 870, owner: "u4", lastContact: 35, inactive: true, customer: true },
 { id: "a8", name: "ConstrutoraIpê", industry: "construction",region: "Centro-Oeste",city: "Goiânia, GO", employees: 290, owner: "u5", lastContact: 4, inactive: false, customer: false },
 { id: "a9", name: "Lacticínios Vale Verde",industry: "food", region: "Sudeste", city: "Juiz de Fora, MG", employees: 380, owner: "u6", lastContact: 6, inactive: false, customer: true },
 { id: "a10", name: "MetalForma Indústria", industry: "metallurgy", region: "Sul", city: "Joinville, SC", employees: 720, owner: "u2", lastContact: 18, inactive: false, customer: false },
 { id: "a11", name: "Alimentos Caatinga", industry: "food", region: "Nordeste", city: "Petrolina, PE", employees: 230, owner: "u3", lastContact: 42, inactive: true, customer: false },
 { id: "a12", name: "Têxtil Bandeirantes", industry: "textile", region: "Sudeste", city: "Americana, SP", employees: 420, owner: "u4", lastContact: 3, inactive: false, customer: false },
 // Contas dummy usadas pelo Mapa de Classificação de Contatos (fidelização)
 { id: "a13", name: "Ferragens Pampa", industry: "metallurgy", region: "Sul", city: "Bagé, RS", employees: 95, owner: "u1", lastContact: 0, inactive: false, customer: false },
 { id: "a14", name: "Alimentos Cerrado Mix", industry: "food", region: "Centro-Oeste", city: "Anápolis, GO", employees: 260, owner: "u2", lastContact: 2, inactive: false, customer: false },
 { id: "a15", name: "PlastiNorte Embalagens", industry: "plastics", region: "Norte", city: "Belém, PA", employees: 180, owner: "u3", lastContact: 2, inactive: false, customer: false },
 { id: "a16", name: "Química Atlântico", industry: "chemistry", region: "Nordeste", city: "Aracaju, SE", employees: 130, owner: "u4", lastContact: 30, inactive: true, customer: false },
 { id: "a17", name: "Auto Componentes Vale", industry: "automotive", region: "Sudeste", city: "Taubaté, SP", employees: 410, owner: "u4", lastContact: 10, inactive: false, customer: false },
 { id: "a18", name: "Têxtil Coqueiros", industry: "textile", region: "Nordeste", city: "Fortaleza, CE", employees: 320, owner: "u5", lastContact: 4, inactive: false, customer: false },
 { id: "a19", name: "Eletro Sul Industrial", industry: "electronics", region: "Sul", city: "Florianópolis, SC", employees: 540, owner: "u6", lastContact: 7, inactive: false, customer: false },
 { id: "a20", name: "Construtora Cerrado", industry: "construction", region: "Centro-Oeste", city: "Brasília, DF", employees: 220, owner: "u1", lastContact: 5, inactive: false, customer: false },
];
// Exponho para módulos via window (classificação precisa cruzar contas/vendedores)
if (typeof window !== "undefined") { window.ACCOUNTS = ACCOUNTS; window.REPS = REPS; }

const DEALS = [
 // new
 { id: "d1", accountId: "a1", name: "Implantação Canal Interno - Aurora", stage: "new", value: 285000, probability: 15, ownerId: "u2", closeIn: 78 },
 { id: "d2", accountId: "a5", name: "Reestruturação SDR - AutoPeças Bahiana", stage: "new", value: 195000, probability: 20, ownerId: "u2", closeIn: 65 },
 { id: "d3", accountId: "a8", name: "Diagnóstico de Canal - Ipê", stage: "new", value: 84000, probability: 25, ownerId: "u5", closeIn: 90 },
 // qualified
 { id: "d4", accountId: "a3", name: "Operação Home Office - QuímicaTech", stage: "qualified", value: 420000, probability: 40, ownerId: "u4", closeIn: 45 },
 { id: "d5", accountId: "a6", name: "Célula Digital - PolyBrasil", stage: "qualified", value: 312000, probability: 45, ownerId: "u3", closeIn: 52 },
 { id: "d6", accountId: "a12", name: "Treinamento In-Company - Bandeirantes", stage: "qualified", value: 68000, probability: 50, ownerId: "u4", closeIn: 30 },
 // proposal
 { id: "d7", accountId: "a10", name: "Canal Interno Completo - MetalForma", stage: "proposal", value: 540000, probability: 60, ownerId: "u2", closeIn: 22 },
 { id: "d8", accountId: "a9", name: "Renovação + Expansão - Vale Verde", stage: "proposal", value: 215000, probability: 65, ownerId: "u6", closeIn: 18 },
 { id: "d9", accountId: "a4", name: "Reativação Canal - Cipriani", stage: "proposal", value: 96000, probability: 55, ownerId: "u5", closeIn: 35 },
 // negotiation
 { id: "d10", accountId: "a2", name: "Expansão Nacional - SulCarne", stage: "negotiation",value: 680000, probability: 75, ownerId: "u3", closeIn: 12 },
 { id: "d11", accountId: "a6", name: "Pesquisa de Mercado - PolyBrasil", stage: "negotiation",value: 145000, probability: 80, ownerId: "u3", closeIn: 8 },
 // won
 { id: "d12", accountId: "a9", name: "Operação Inside Sales - Vale Verde", stage: "won", value: 320000, probability: 100, ownerId: "u6", closeIn: -3 },
 { id: "d13", accountId: "a7", name: "Diagnóstico - EletroMaster", stage: "won", value: 78000, probability: 100, ownerId: "u4", closeIn: -8 },
];

const ACTIVITIES = [
 { id: "ac1", type: "call", accountId: "a10", ownerId: "u2", text: "Ligação de descoberta com Diretor Comercial", time: "há 14 min" },
 { id: "ac2", type: "email", accountId: "a3", ownerId: "u4", text: "Proposta enviada — Operação Home Office", time: "há 1 h" },
 { id: "ac3", type: "meeting", accountId: "a2", ownerId: "u3", text: "Reunião de fechamento agendada", time: "há 2 h" },
 { id: "ac4", type: "stage", accountId: "a6", ownerId: "u3", text: "Movido para Negociação", time: "há 3 h" },
 { id: "ac5", type: "note", accountId: "a4", ownerId: "u5", text: "Cliente solicitou revisão de cláusula 4.2", time: "ontem" },
 { id: "ac6", type: "won", accountId: "a9", ownerId: "u6", text: "Oportunidade ganha — R$ 320k", time: "ontem" },
];

const UPCOMING = [
 { day: "qua", date: 21, time: "09:00", type: "call", title: "Discovery — Aurora", color: "teal", rep: "DA" },
 { day: "qua", date: 21, time: "11:30", type: "meeting", title: "Demo — QuímicaTech", color: "", rep: "RC" },
 { day: "qua", date: 21, time: "14:00", type: "call", title: "Follow-up — PolyBrasil", color: "teal", rep: "JM" },
 { day: "qui", date: 22, time: "10:00", type: "meeting", title: "Fechamento — SulCarne", color: "success", rep: "JM" },
 { day: "qui", date: 22, time: "15:30", type: "call", title: "Reativação — Cipriani", color: "warn", rep: "MT" },
 { day: "sex", date: 23, time: "09:30", type: "meeting", title: "Kickoff — Vale Verde", color: "success", rep: "LV" },
 { day: "sex", date: 23, time: "16:00", type: "call", title: "Negociação — MetalForma", color: "", rep: "DA" },
];

// 12-month revenue + forecast series
const REVENUE_SERIES = [
 { m: "jan", actual: 2.8, forecast: null },
 { m: "fev", actual: 3.1, forecast: null },
 { m: "mar", actual: 3.6, forecast: null },
 { m: "abr", actual: 3.4, forecast: null },
 { m: "mai", actual: 4.1, forecast: null },
 { m: "jun", actual: 4.4, forecast: null },
 { m: "jul", actual: 4.0, forecast: null },
 { m: "ago", actual: 4.6, forecast: null },
 { m: "set", actual: 5.1, forecast: null },
 { m: "out", actual: 4.8, forecast: null },
 { m: "nov", actual: null, forecast: 5.4 },
 { m: "dez", actual: null, forecast: 5.9 },
];

const FUNNEL = [
 { stage: "new", count: 184, value: 8.4 },
 { stage: "qualified", count: 96, value: 5.6 },
 { stage: "proposal", count: 48, value: 3.8 },
 { stage: "negotiation", count: 22, value: 2.1 },
 { stage: "won", count: 14, value: 1.6 },
];

const SEGMENT_PERF = [
 { id: "metallurgy", revenue: 1.8, deals: 14 },
 { id: "food", revenue: 1.4, deals: 11 },
 { id: "chemistry", revenue: 1.1, deals: 8 },
 { id: "automotive", revenue: 0.9, deals: 7 },
 { id: "plastics", revenue: 0.7, deals: 6 },
 { id: "textile", revenue: 0.4, deals: 4 },
];

const TERRITORY_PINS = [
 // Approx % coords on a stylized BR map (left,top)
 { region: "Sul", x: 36, y: 80, accounts: 9, deals: 7, revenue: 2.1 },
 { region: "Sudeste", x: 52, y: 67, accounts: 14, deals: 11, revenue: 3.4 },
 { region: "Centro-Oeste", x: 42, y: 55, accounts: 5, deals: 3, revenue: 0.8 },
 { region: "Nordeste", x: 64, y: 35, accounts: 7, deals: 4, revenue: 1.2 },
 { region: "Norte", x: 40, y: 25, accounts: 3, deals: 2, revenue: 0.6 },
];

// Per-rep performance
const REP_PERF = REPS.map((r, i) => ({
 ...r,
 quota: [800, 750, 600, 550, 450, 400][i],
 closed: [920, 680, 540, 420, 380, 240][i],
 deals: [11, 9, 7, 6, 5, 3][i],
 calls: [186, 142, 124, 98, 88, 64][i],
 meetings: [22, 18, 14, 11, 10, 7][i],
 winRate: [42, 38, 35, 31, 28, 22][i],
}));

// Buying behavior history for detail screen
const BUYING_HISTORY = [
 { month: "Jul", orders: 4, value: 86 },
 { month: "Ago", orders: 5, value: 102 },
 { month: "Set", orders: 6, value: 118 },
 { month: "Out", orders: 4, value: 94 },
 { month: "Nov", orders: 7, value: 142 },
 { month: "Dez", orders: 8, value: 168 },
];

// ============================================================
// World map pins — clientes/leads/prospects em coords (x%, y%)
// ============================================================
const GLOBAL_PINS = [
 // Brasil — Sul/Sudeste densos
 { id: "g1", city: "Porto Alegre, BR", lat: -30.0346, lng: -51.2177, x: 39, y: 79, status: "customer", segment: "metallurgy", rep: "u2", value: 320 },
 { id: "g2", city: "Caxias do Sul, BR", lat: -29.1685, lng: -51.1796, x: 39.5, y: 77, status: "lead", segment: "metallurgy", rep: "u2", value: 285 },
 { id: "g3", city: "Joinville, BR", lat: -26.3045, lng: -48.8487, x: 40, y: 74, status: "lead", segment: "metallurgy", rep: "u2", value: 540 },
 { id: "g4", city: "São Paulo, BR", lat: -23.5505, lng: -46.6333, x: 41, y: 72, status: "customer", segment: "automotive", rep: "u3", value: 460 },
 { id: "g5", city: "Campinas, BR", lat: -22.9099, lng: -47.0626, x: 40.5, y: 71, status: "lead", segment: "chemistry", rep: "u4", value: 420 },
 { id: "g6", city: "Rio de Janeiro, BR", lat: -22.9068, lng: -43.1729, x: 42, y: 72, status: "prospect", segment: "food", rep: "u3", value: 0 },
 { id: "g7", city: "Belo Horizonte, BR", lat: -19.9167, lng: -43.9345, x: 41, y: 69, status: "customer", segment: "food", rep: "u6", value: 215 },
 { id: "g8", city: "Goiânia, BR", lat: -16.6869, lng: -49.2648, x: 39, y: 67, status: "lead", segment: "construction",rep: "u5", value: 84 },
 { id: "g9", city: "Brasília, BR", lat: -15.7942, lng: -47.8822, x: 40, y: 66, status: "prospect", segment: "construction",rep: "u5", value: 0 },
 { id: "g10", city: "Salvador, BR", lat: -12.9714, lng: -38.5014, x: 44, y: 60, status: "prospect", segment: "chemistry", rep: "u4", value: 0 },
 { id: "g11", city: "Recife, BR", lat: -8.0476, lng: -34.8770, x: 46, y: 56, status: "lead", segment: "food", rep: "u3", value: 68 },
 { id: "g12", city: "Fortaleza, BR", lat: -3.7319, lng: -38.5267, x: 45, y: 54, status: "prospect", segment: "textile", rep: "u4", value: 0 },
 { id: "g13", city: "Manaus, BR", lat: -3.1190, lng: -60.0217, x: 38, y: 56, status: "inactive", segment: "electronics",rep: "u4", value: 0 },
 { id: "g14", city: "Belém, BR", lat: -1.4558, lng: -48.5039, x: 41, y: 53, status: "prospect", segment: "food", rep: "u3", value: 0 },
 // Argentina, Chile, Uruguai, Paraguai
 { id: "g15", city: "Buenos Aires, AR", lat: -34.6037, lng: -58.3816, x: 37, y: 83, status: "lead", segment: "automotive", rep: "u2", value: 180 },
 { id: "g16", city: "Santiago, CL", lat: -33.4489, lng: -70.6693, x: 34, y: 82, status: "prospect", segment: "metallurgy", rep: "u2", value: 0 },
 { id: "g17", city: "Montevideo, UY", lat: -34.9011, lng: -56.1645, x: 38, y: 82, status: "prospect", segment: "food", rep: "u3", value: 0 },
 { id: "g18", city: "Asunción, PY", lat: -25.2637, lng: -57.5759, x: 38, y: 75, status: "lead", segment: "food", rep: "u3", value: 95 },
 // México / Colombia
 { id: "g19", city: "Cidade do México, MX", lat: 19.4326, lng: -99.1332, x: 24, y: 51, status: "prospect", segment: "automotive", rep: "u2", value: 0 },
 { id: "g20", city: "Bogotá, CO", lat: 4.7110, lng: -74.0721, x: 33, y: 56, status: "prospect", segment: "chemistry", rep: "u4", value: 0 },
 // Europa / outros (3lackd já implantou alguns canais lá)
 { id: "g21", city: "Lisboa, PT", lat: 38.7223, lng: -9.1393, x: 51, y: 41, status: "lead", segment: "metallurgy", rep: "u2", value: 220 },
 { id: "g22", city: "Madri, ES", lat: 40.4168, lng: -3.7038, x: 53, y: 40, status: "prospect", segment: "automotive", rep: "u3", value: 0 },
 { id: "g23", city: "Milão, IT", lat: 45.4642, lng: 9.1900, x: 56, y: 38, status: "prospect", segment: "textile", rep: "u4", value: 0 },
 // Mais clientes — Brasil ampliado
 { id: "g24", city: "Novo Hamburgo, BR", lat: -29.6783, lng: -51.1308, x: 39, y: 79, status: "customer", segment: "textile", rep: "u2", value: 175 },
 { id: "g25", city: "Pelotas, BR", lat: -31.7654, lng: -52.3376, x: 38, y: 81, status: "lead", segment: "food", rep: "u2", value: 120 },
 { id: "g26", city: "Santa Maria, BR", lat: -29.6842, lng: -53.8069, x: 37, y: 79, status: "prospect", segment: "construction",rep: "u2", value: 0 },
 { id: "g27", city: "Florianópolis, BR", lat: -27.5949, lng: -48.5482, x: 40, y: 75, status: "customer", segment: "electronics", rep: "u2", value: 390 },
 { id: "g28", city: "Blumenau, BR", lat: -26.9194, lng: -49.0661, x: 40, y: 74, status: "lead", segment: "textile", rep: "u2", value: 245 },
 { id: "g29", city: "Chapecó, BR", lat: -27.0967, lng: -52.6184, x: 38, y: 75, status: "customer", segment: "food", rep: "u2", value: 410 },
 { id: "g30", city: "Curitiba, BR", lat: -25.4284, lng: -49.2733, x: 40, y: 73, status: "customer", segment: "automotive", rep: "u3", value: 520 },
 { id: "g31", city: "Londrina, BR", lat: -23.3045, lng: -51.1696, x: 39, y: 72, status: "lead", segment: "food", rep: "u3", value: 180 },
 { id: "g32", city: "Maringá, BR", lat: -23.4205, lng: -51.9333, x: 39, y: 72, status: "prospect", segment: "construction",rep: "u3", value: 0 },
 { id: "g33", city: "Ribeirão Preto, BR", lat: -21.1775, lng: -47.8103, x: 41, y: 70, status: "customer", segment: "chemistry", rep: "u4", value: 360 },
 { id: "g34", city: "São José dos Campos, BR", lat: -23.2237, lng: -45.9009, x: 41, y: 71, status: "lead", segment: "electronics", rep: "u3", value: 295 },
 { id: "g35", city: "Uberlândia, BR", lat: -18.9186, lng: -48.2772, x: 40, y: 68, status: "customer", segment: "automotive", rep: "u6", value: 305 },
 { id: "g36", city: "Vitória, BR", lat: -20.3155, lng: -40.3128, x: 43, y: 69, status: "lead", segment: "metallurgy", rep: "u6", value: 230 },
 { id: "g37", city: "João Pessoa, BR", lat: -7.1195, lng: -34.8450, x: 46, y: 55, status: "prospect", segment: "textile", rep: "u3", value: 0 },
 { id: "g38", city: "Natal, BR", lat: -5.7945, lng: -35.2110, x: 47, y: 55, status: "lead", segment: "construction",rep: "u3", value: 95 },
 { id: "g39", city: "Cuiabá, BR", lat: -15.6010, lng: -56.0974, x: 37, y: 64, status: "prospect", segment: "construction",rep: "u5", value: 0 },
 { id: "g40", city: "Campo Grande, BR", lat: -20.4697, lng: -54.6201, x: 37, y: 68, status: "lead", segment: "food", rep: "u5", value: 140 },
 { id: "g41", city: "Porto Velho, BR", lat: -8.7619, lng: -63.9039, x: 36, y: 58, status: "prospect", segment: "construction",rep: "u4", value: 0 },
 { id: "g42", city: "São Luís, BR", lat: -2.5307, lng: -44.3068, x: 43, y: 54, status: "prospect", segment: "food", rep: "u3", value: 0 },
 { id: "g43", city: "Teresina, BR", lat: -5.0892, lng: -42.8019, x: 43, y: 55, status: "prospect", segment: "food", rep: "u3", value: 0 },
];

// Regional "heat" data — used both para o mapa-mundi e relatórios
const HEAT_REGIONS = [
 { id: "br-sul", label: "Brasil · Sul", customers: 9, leads: 7, prospects: 3, revenue: 2.1, heat: "hot", lat: -29.5, lng: -51.0, x: 40, y: 78 },
 { id: "br-sudeste", label: "Brasil · Sudeste", customers: 14, leads: 11, prospects: 6, revenue: 3.4, heat: "hot", lat: -22.5, lng: -45.5, x: 41, y: 71 },
 { id: "br-co", label: "Brasil · Centro-O.", customers: 5, leads: 3, prospects: 4, revenue: 0.8, heat: "warm", lat: -15.8, lng: -49.0, x: 40, y: 66 },
 { id: "br-nordeste", label: "Brasil · Nordeste", customers: 7, leads: 4, prospects: 5, revenue: 1.2, heat: "warm", lat: -9.0, lng: -36.0, x: 45, y: 56 },
 { id: "br-norte", label: "Brasil · Norte", customers: 3, leads: 2, prospects: 4, revenue: 0.6, heat: "cold", lat: -3.5, lng: -55.0, x: 40, y: 54 },
 { id: "cone-sul", label: "Cone Sul", customers: 2, leads: 2, prospects: 3, revenue: 0.4, heat: "warm", lat: -34.6, lng: -58.4, x: 37, y: 82 },
 { id: "andina", label: "Região Andina", customers: 0, leads: 0, prospects: 2, revenue: 0.0, heat: "cold", lat: 4.7, lng: -74.0, x: 33, y: 57 },
 { id: "mexico-am", label: "México / América C.",customers: 0, leads: 0, prospects: 1, revenue: 0.0, heat: "cold", lat: 19.4, lng: -99.1, x: 24, y: 51 },
 { id: "europa-iberica",label: "Europa Ibérica", customers: 1, leads: 1, prospects: 1, revenue: 0.3, heat: "warm", lat: 40.0, lng: -5.0, x: 52, y: 40 },
];

// Catálogo de produtos / serviços 3lackd
const PRODUCTS = [
 {
 id: "p1",
 name: "Implantação de Canal Interno B2B",
 sku: "VZZ-IMPL-001",
 category: "Implantação",
 summary: "Estruturação completa de operação de inside sales para indústria, do diagnóstico ao primeiro ciclo comercial fechado.",
 price: "R$ 48.500 / projeto",
 unit: "Projeto · 6 meses",
 coverage: "Nacional",
 team: "8 especialistas dedicados",
 duration: "180 dias",
 deliverables: [
 "Diagnóstico do canal atual",
 "Política comercial e contratos",
 "Recrutamento e seleção da equipe",
 "Playbook e cadência operacional",
 "Implantação de ferramentas e CRM",
 "Acompanhamento dos primeiros 90 dias",
 ],
 targetSize: "Indústrias com 50+ colaboradores",
 recommendation: "Recomendado para indústrias que dependem 100% de representantes externos e buscam previsibilidade de receita.",
 tag: "Mais vendido",
 color: "#2EBFC5",
 image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&q=70",
 },
 {
 id: "p2",
 name: "Operação Home Office (Célula Digital)",
 sku: "VZZ-HMO-002",
 category: "Operação",
 summary: "Time remoto de inside sales operado pela 3lackd, com mensalidade fixa + comissão variável.",
 price: "A partir de R$ 38.500 / mês",
 unit: "Mensal · contrato 12 meses",
 coverage: "Nacional / LATAM",
 team: "3 SDRs + 1 closer + coord.",
 duration: "Contínuo",
 deliverables: [
 "Recrutamento e gestão da célula",
 "Infraestrutura de telefonia (3CX)",
 "WhatsApp Business integrado",
 "Relatórios semanais de cadência",
 "Sincronização com ERP",
 ],
 targetSize: "Indústrias com mix de produtos médio-baixo",
 recommendation: "Ideal para complementar representantes em territórios com baixa cobertura.",
 tag: "Premium",
 color: "#3F5BA8",
 image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&q=70",
 },
 {
 id: "p3",
 name: "Diagnóstico + Pesquisa de Mercado",
 sku: "VZZ-DIAG-003",
 category: "Consultoria",
 summary: "Pesquisa quantitativa e qualitativa para mapear comportamento de compra e oportunidades.",
 price: "R$ 18.900 / pesquisa",
 unit: "Pesquisa · 45 dias",
 coverage: "Nacional",
 team: "Analista sênior + 2 analistas",
 duration: "45 dias",
 deliverables: [
 "Pesquisa com 200+ compradores",
 "Mapa de concorrência",
 "Comportamento de compra detalhado",
 "Plano de ação com prioridades",
 ],
 targetSize: "Qualquer porte",
 recommendation: "Use antes de uma implantação para validar premissas e dimensionar o canal.",
 tag: "",
 color: "#7B5BC8",
 image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=70",
 },
 {
 id: "p4",
 name: "Treinamento In-Company (Vendas Consultivas)",
 sku: "VZZ-TRN-004",
 category: "Treinamento",
 summary: "Programa de 32 horas com a metodologia 3lackd de venda consultiva para indústria.",
 price: "R$ 12.500 / turma (até 20 alunos)",
 unit: "Turma · 32h presenciais",
 coverage: "Nacional",
 team: "1 instrutor certificado",
 duration: "32 horas (4 dias)",
 deliverables: [
 "Workbook personalizado",
 "Role-plays gravados",
 "Certificação individual",
 "Follow-up 30 dias após",
 ],
 targetSize: "Equipes de 8-20 vendedores",
 recommendation: "Pode ser contratado isolado ou como módulo da implantação.",
 tag: "",
 color: "#D88514",
 image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=70",
 },
 {
 id: "p5",
 name: "Reestruturação de Canal Existente",
 sku: "VZZ-REE-005",
 category: "Consultoria",
 summary: "Para indústrias que já têm canal interno mas precisam revisar processos, equipe e ferramentas.",
 price: "R$ 32.000 / projeto",
 unit: "Projeto · 90 dias",
 coverage: "Nacional",
 team: "5 especialistas",
 duration: "90 dias",
 deliverables: [
 "Auditoria operacional",
 "Redesenho de processos",
 "Plano de transição de pessoas",
 "Métricas e ritual gerencial",
 ],
 targetSize: "Operações com 3+ anos",
 recommendation: "Indicado quando há queda de produtividade ou alta rotatividade no canal.",
 tag: "",
 color: "#16A07C",
 image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=70",
 },
 {
 id: "p6",
 name: "Gestão de Conflito Canal × Representante",
 sku: "VZZ-CFL-006",
 category: "Consultoria",
 summary: "Mediação e construção de política de comissão que reduz atrito entre canal interno e representantes externos.",
 price: "R$ 14.500 / projeto",
 unit: "Projeto · 60 dias",
 coverage: "Nacional",
 team: "2 consultores sêniores",
 duration: "60 dias",
 deliverables: [
 "Política de comissão revisada",
 "Contratos atualizados",
 "Workshop com representantes",
 "Régua de comunicação",
 ],
 targetSize: "Indústrias com 10+ representantes",
 recommendation: "Especialmente útil em verticais com territórios sobrepostos.",
 tag: "",
 color: "#D63B5C",
 image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&q=70",
 },
 {
 id: "p7", name: "Implantação de CRM Industrial", sku: "VZZ-CRM-007", category: "Implantação",
 summary: "Configuração do CRM 3lackd adaptado ao ciclo longo de vendas industriais, com integração ao ERP.",
 price: "R$ 22.500 / projeto", unit: "Projeto · 60 dias", coverage: "Nacional",
 team: "2 implantadores + 1 arquiteto", duration: "60 dias",
 deliverables: ["Modelagem do pipeline", "Cadastro de produtos e regras", "Integração com ERP", "Treinamento da equipe"],
 targetSize: "Indústrias de qualquer porte",
 recommendation: "Ideal quando a equipe perde negócios por falta de visibilidade no funil.",
 tag: "", color: "#2EBFC5",
 image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=70",
 },
 {
 id: "p8", name: "BPO de Pré-venda (SDR as a Service)", sku: "VZZ-SDR-008", category: "Operação",
 summary: "Time de SDRs treinados pela 3lackd qualificando leads e agendando reuniões para o seu closer.",
 price: "A partir de R$ 18.900 / mês", unit: "Mensal · contrato 6 meses", coverage: "Nacional",
 team: "2 SDRs + supervisor", duration: "Contínuo",
 deliverables: ["Cadência outbound + inbound", "Script personalizado", "200+ atividades/dia", "Relatórios semanais"],
 targetSize: "Empresas com ticket médio acima de R$ 30k",
 recommendation: "Solução plug-and-play para acelerar geração de pipeline.",
 tag: "Novo", color: "#3F5BA8",
 image: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=600&q=70",
 },
 {
 id: "p9", name: "Mentoria para Gestores Comerciais", sku: "VZZ-MNT-009", category: "Treinamento",
 summary: "Encontros quinzenais 1:1 com mentores 3lackd para gerentes e coordenadores comerciais.",
 price: "R$ 4.800 / mês por gestor", unit: "Mensal · ciclo de 6 meses", coverage: "Nacional",
 team: "Mentor sênior dedicado", duration: "6 meses",
 deliverables: ["Encontros 1:1 quinzenais", "Plano de desenvolvimento", "Acompanhamento de KPIs", "Acesso à biblioteca 3lackd"],
 targetSize: "Gestores de equipes de 5+ vendedores",
 recommendation: "Recomendado para gestores promovidos recentemente.",
 tag: "", color: "#D88514",
 image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=600&q=70",
 },
 {
 id: "p10", name: "Auditoria de Pipeline e Forecast", sku: "VZZ-AUD-010", category: "Consultoria",
 summary: "Revisão técnica do funil para validar previsibilidade de receita do próximo trimestre.",
 price: "R$ 9.500 / auditoria", unit: "Avulsa · 15 dias", coverage: "Nacional",
 team: "1 sênior + 1 analista", duration: "15 dias",
 deliverables: ["Higienização do pipeline", "Análise de probabilidade real", "Forecast revisado", "Relatório executivo"],
 targetSize: "Empresas com 50+ deals abertos",
 recommendation: "Ideal antes de planejamento anual ou reporte ao board.",
 tag: "", color: "#7B5BC8",
 image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=70&sat=-50",
 },
 {
 id: "p11", name: "Implantação de Telefonia 3CX", sku: "VZZ-TEL-011", category: "Implantação",
 summary: "Infraestrutura completa de telefonia VoIP integrada ao CRM, com gravação e relatórios.",
 price: "R$ 14.800 / projeto + mensal", unit: "Projeto · 30 dias", coverage: "Nacional",
 team: "1 engenheiro VoIP", duration: "30 dias",
 deliverables: ["Configuração 3CX", "Ramais e filas", "Gravação de chamadas", "Dashboard de métricas"],
 targetSize: "Operações com 5+ posições",
 recommendation: "Pré-requisito para operações de inside sales escaláveis.",
 tag: "", color: "#16A07C",
 image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=600&q=70",
 },
 {
 id: "p12", name: "Workshop de Negociação Industrial", sku: "VZZ-NEG-012", category: "Treinamento",
 summary: "Imersão de 16h focada em negociações complexas B2B com múltiplos decisores.",
 price: "R$ 8.900 / turma (até 15 alunos)", unit: "Turma · 16h presenciais", coverage: "Nacional",
 team: "1 instrutor especialista", duration: "16 horas (2 dias)",
 deliverables: ["Cases reais de indústria", "Simulações filmadas", "Material de apoio", "Certificação"],
 targetSize: "Vendedores e key account managers",
 recommendation: "Indicado para equipes que negociam contratos acima de R$ 100k.",
 tag: "", color: "#D63B5C",
 image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&q=70",
 },
 {
 id: "p13", name: "Diagnóstico de Customer Success", sku: "VZZ-CS-013", category: "Consultoria",
 summary: "Mapeamento da jornada pós-venda e identificação de pontos de churn e expansão.",
 price: "R$ 16.500 / projeto", unit: "Projeto · 30 dias", coverage: "Nacional",
 team: "1 CSM sênior + analista", duration: "30 dias",
 deliverables: ["Mapa da jornada atual", "Indicadores de saúde", "Playbook de retenção", "Plano de upsell"],
 targetSize: "Empresas com base de 50+ clientes ativos",
 recommendation: "Ideal quando a taxa de churn ultrapassa 8% ao ano.",
 tag: "", color: "#2EBFC5",
 image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=70",
 },
 {
 id: "p14", name: "Recrutamento de Vendedores Técnicos", sku: "VZZ-REC-014", category: "Operação",
 summary: "Hunting especializado em vendedores com background técnico para indústria.",
 price: "R$ 12.000 / vaga (1 salário)", unit: "Por vaga preenchida", coverage: "Nacional",
 team: "1 recrutador especialista", duration: "30-45 dias",
 deliverables: ["Briefing aprofundado", "Triagem técnica", "Entrevistas comportamentais", "Garantia de 90 dias"],
 targetSize: "Vagas de vendedor sênior ou KAM",
 recommendation: "Use quando você não tem perfil técnico para avaliar candidatos.",
 tag: "", color: "#3F5BA8",
 image: "https://images.unsplash.com/photo-1573164713988-8665fc963095?w=600&q=70",
 },
 {
 id: "p15", name: "Pacote Anual 3lackd Enterprise", sku: "VZZ-ENT-015", category: "Operação",
 summary: "Contrato anual incluindo implantação, operação, treinamento contínuo e suporte premium.",
 price: "Sob consulta · a partir de R$ 480k/ano", unit: "Anual", coverage: "Nacional / LATAM",
 team: "Squad dedicado de 12+", duration: "12 meses renovável",
 deliverables: ["Tudo do plano Premium", "SLA dedicado", "Roadmap trimestral", "Workshops in-company", "Acesso a beta features"],
 targetSize: "Indústrias com faturamento R$ 100M+",
 recommendation: "Para empresas que vêem a 3lackd como parceiro estratégico de longo prazo.",
 tag: "Enterprise", color: "#16A07C",
 image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=70",
 },
];

// Mensagens / templates
const MSG_TEMPLATES = {
 whatsapp: [
 { id: "wp1", title: "Primeiro contato", text: "Olá {nome}, tudo bem? Sou da 3lackd — implantamos canais internos de vendas para a indústria. Tenho 15 minutos esta semana para entender se faz sentido conversarmos? Posso explicar como já reestruturamos canais semelhantes ao da {empresa}." },
 { id: "wp2", title: "Follow-up de proposta", text: "Oi {nome}! Passando para saber se conseguiu olhar a proposta que enviei na quarta. Posso esclarecer qualquer ponto agora, e tenho horário disponível amanhã às 10h ou 15h para fechar os detalhes." },
 { id: "wp3", title: "Reativação", text: "Olá {nome}, faz {dias} dias desde nosso último contato. Tudo certo do seu lado? Houve mudanças importantes aqui na 3lackd que podem interessar à {empresa} — vale uma call de 10 min?" },
 { id: "wp4", title: "Convite para reunião", text: "Boa tarde {nome}! Reservei um horário na quinta às 14h para apresentarmos o diagnóstico do seu canal atual. Confirma para mim?" },
 ],
 email: [
 { id: "em1", title: "Proposta comercial", text: "Prezado(a) {nome},\n\nSegue em anexo a proposta de implantação do canal interno de vendas para a {empresa}. O escopo cobre os 6 meses de operação, com acompanhamento da 3lackd nos primeiros 90 dias de cadência.\n\nFico à disposição para alinhamentos.\n\nAtenciosamente,\nCamila Reis" },
 { id: "em2", title: "Resumo de reunião", text: "Prezado(a) {nome},\n\nObrigada pela disponibilidade hoje. Como combinado, seguem os próximos passos:\n\n• Envio do diagnóstico até sexta\n• Visita técnica na primeira quinzena\n• Apresentação de proposta na semana 3\n\nQualquer dúvida estou à disposição.\n\nAbraços,\nCamila Reis" },
 { id: "em3", title: "Reativação executiva", text: "Olá {nome},\n\nFaz algum tempo que não conversamos. Como anda o canal comercial da {empresa}? Tenho cases recentes de indústrias que reestruturaram a operação interna e ganharam 18-25% de previsibilidade — gostaria de compartilhar contigo.\n\nPosso enviar um material resumido ou agendar 20 min na sua agenda?\n\nAbraços,\nCamila Reis" },
 ],
};

// Roteirização — pontos do dia atual com endereço + lat/lng (aprox %)
// Origem padrão da roteirização (sede do vendedor)
const ROUTE_ORIGIN = { label: "São Leopoldo, RS · sede do vendedor", lat: -29.7587, lng: -51.1467 };

// Roteirização — apenas clientes próximos da região do vendedor (RS / SC)
const ROUTE_CLIENTS = [
 { id: "r1", account: "Metalúrgica Aurora", addr: "Av. das Indústrias, 2400 · Caxias do Sul/RS", lat: -29.1685, lng: -51.1796, alert: true, inactive: 0, category: "Diagnóstico em curso", transit: 55, value: 285, last: "há 2 dias" },
 { id: "r2", account: "Calçados Novo Horizonte", addr: "R. Lima e Silva, 1200 · Novo Hamburgo/RS", lat: -29.6783, lng: -51.1308, alert: false, inactive: 7, category: "Fechamento", transit: 12, value: 165, last: "há 7 dias" },
 { id: "r3", account: "MetalSul Indústria", addr: "Rod. RS-118, km 12 · Gravataí/RS", lat: -29.9442, lng: -50.9919, alert: false, inactive: 4, category: "Visita técnica", transit: 22, value: 240, last: "há 4 dias" },
 { id: "r4", account: "Vinícola Serra Bento", addr: "Linha Leopoldina · Bento Gonçalves/RS", lat: -29.1714, lng: -51.5191, alert: false, inactive: 9, category: "Kickoff de operação", transit: 75, value: 320, last: "há 9 dias" },
 { id: "r5", account: "Frigorífico SulCarne", addr: "BR-285, km 290 · Passo Fundo/RS", lat: -28.2628, lng: -52.4067, alert: false, inactive: 5, category: "Fechamento", transit: 165, value: 680, last: "há 5 dias" },
 { id: "r6", account: "QuímicaVale RS", addr: "Av. Independência · Lajeado/RS", lat: -29.4669, lng: -51.9614, alert: true, inactive: 24, category: "Reativação", transit: 65, value: 195, last: "há 24 dias" },
 { id: "r7", account: "Têxtil Santa Cruz", addr: "R. Marechal Floriano · Santa Cruz do Sul/RS", lat: -29.7175, lng: -52.4250, alert: false, inactive: 11, category: "Demo técnica", transit: 90, value: 130, last: "há 11 dias" },
 { id: "r8", account: "Plásticos Litoral RS", addr: "Av. Assis Brasil · Esteio/RS", lat: -29.8606, lng: -51.1761, alert: false, inactive: 3, category: "Visita técnica", transit: 18, value: 88, last: "há 3 dias" },
 { id: "r9", account: "Indústrias Sapiranga", addr: "R. João Pessoa · Sapiranga/RS", lat: -29.6378, lng: -50.9908, alert: false, inactive: 6, category: "Apresentação inicial", transit: 28, value: 110, last: "há 6 dias" },
 { id: "r10", account: "AgroSul Cooperativa", addr: "BR-386, km 410 · Carazinho/RS", lat: -28.2841, lng: -52.7864, alert: true, inactive: 32, category: "Reativação", transit: 175, value: 420, last: "há 32 dias" },
 { id: "r11", account: "MetalForma Indústria", addr: "Rod. SC-401, km 18 · Joinville/SC", lat: -26.3045, lng: -48.8487, alert: false, inactive: 18, category: "Visita de proposta", transit: 280, value: 540, last: "há 18 dias" },
 { id: "r12", account: "Tecidos Cipriani", addr: "R. Felipe Schmidt, 880 · Brusque/SC", lat: -27.0980, lng: -48.9176, alert: true, inactive: 28, category: "Reativação", transit: 240, value: 96, last: "há 28 dias" },
 { id: "r13", account: "Eletro Blumenau", addr: "R. XV de Novembro · Blumenau/SC", lat: -26.9194, lng: -49.0661, alert: false, inactive: 14, category: "Demo técnica", transit: 250, value: 245, last: "há 14 dias" },
 { id: "r14", account: "Pesca & Cia", addr: "Av. Beira-Mar · Florianópolis/SC", lat: -27.5949, lng: -48.5482, alert: false, inactive: 8, category: "Kickoff de operação", transit: 290, value: 390, last: "há 8 dias" },
];

Object.assign(window, {
 I18N, STAGES, INDUSTRIES, REGIONS, REPS, ACCOUNTS, DEALS, ACTIVITIES,
 UPCOMING, REVENUE_SERIES, FUNNEL, SEGMENT_PERF, TERRITORY_PINS, REP_PERF, BUYING_HISTORY,
 GLOBAL_PINS, HEAT_REGIONS, PRODUCTS, MSG_TEMPLATES, ROUTE_CLIENTS, ROUTE_ORIGIN
});
